<?php get_header();$all=eph_collections();$search=eph_input('pesquisa');$collections=array_values(array_filter($all,function($c)use($search){return $search===''||mb_stripos($c->post_title.' '.wp_strip_all_tags($c->post_content),$search)!==false;}));$page=max(1,absint(eph_input('pagina','1')));$total=count($collections); ?>
<main class="eph-public-page"><p class="eph-eyebrow">Explorar o arquivo</p><h1>Coleções</h1><p class="eph-lead">Conheça os conjuntos disponíveis ou <a href="<?php echo esc_url(home_url('/catalogo/')); ?>">pesquise em todo o catálogo</a>.</p>
<form class="eph-global-search eph-directory-search" action="<?php echo esc_url(home_url('/colecoes/')); ?>" method="get"><label class="screen-reader-text" for="collection-search">Procurar uma coleção</label><input id="collection-search" name="pesquisa" type="search" placeholder="Procurar uma coleção…" value="<?php echo esc_attr($search); ?>"><button>Procurar</button></form>
<p class="eph-meta"><?php echo $total; ?> <?php echo $total===1?'coleção disponível':'coleções disponíveis'; ?></p>
<div class="eph-catalogue-grid"><?php foreach(array_slice($collections,($page-1)*12,12) as $c):$items=ephemera_poc_items($c->ID);$cover=get_post_thumbnail_id($c->ID)?:get_post_thumbnail_id($items[0]->ID); ?>
<article class="eph-catalogue-card"><a class="eph-card-image" href="<?php echo esc_url(get_permalink($c)); ?>" tabindex="-1" aria-hidden="true"><?php if($cover)echo wp_get_attachment_image($cover,'medium_large',false,['loading'=>'lazy','alt'=>'']);else echo '<span class="eph-no-image">Coleção</span>'; ?></a><div><p class="eph-meta"><?php echo ephemera_poc_count($c->ID); ?> registos</p><h2><a href="<?php echo esc_url(get_permalink($c)); ?>"><?php echo esc_html($c->post_title); ?></a></h2><a class="eph-more" href="<?php echo esc_url(add_query_arg('colecao',$c->ID,home_url('/catalogo/'))); ?>">Pesquisar nesta coleção →</a></div></article>
<?php endforeach; ?></div>
<?php if(!$total): ?><p>Não foram encontradas coleções. <a href="<?php echo esc_url(home_url('/colecoes/')); ?>">Ver todas as coleções</a>.</p><?php endif; eph_pagination((int)ceil($total/12),$page); ?>
</main><?php get_footer(); ?>
